- README.md
This adds some instructions on how to migrate to the new custom tap for those that installed `pdk` or `bolt` before this existed.
> Add migration instructions

- Casks/pdk.rb
Switching the MacOS version check from a case statement to a standard
if/else block because the MacOS.version is able to compare against
symbols or version string, which may be causing an issue as the subject
of a case statement.
For reference:
https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/readme.md
> Update PDK cask handling of MacOS version

- Casks/puppet-bolt.rb
Update Version and SHA for homebrew.
> (BOLT-668) Update to puppet-bolt 0.21.2

- Casks/puppet-agent.rb
- README.md
Effectively the old cask that was in the homebrew-cask project with a version bump to latest release, a removal of the deprecated appcast checkpoint stanza, and a fix to the new documentation URLs.
Should note that I also only tested on my machine (macOS 10.13), but I did update the checksum for 10.12.
> Add puppet-agent cask

- Casks/pdk.rb
- Casks/puppet-agent.rb
- Casks/puppet-bolt.rb
- Rakefile
- templates/pdk.rb.erb
- templates/puppet-agent.rb.erb
- templates/puppet-bolt.rb.erb
- templates/source_stanza.erb
Updates the Rake task to generate casks to support differing versions
for puppet-agent. Add a new puppet-agent template. Regenerate all casks.
> (maint) Update cask generation to support puppet-agent

- .travis.yml
- Casks/pdk.rb
- Casks/puppet-agent-5.rb
- Casks/puppet-agent-6.rb
- Casks/puppet-agent.rb
- Casks/puppet-bolt.rb
- README.md
- Rakefile
- templates/puppet-agent-5.rb.erb
- templates/puppet-agent-6.rb.erb
- templates/source_stanza.erb
Updates the `puppet-agent` cask to track the `puppet` collection, which
is an alias to the latest versioned collection. Adds `puppet-agent-5`
and `puppet-agent-6` casks tracking the `puppet5` and `puppet6`
collections.
> Add support for multiple Puppet collections

- .travis.yml
Homebrew regression: https://github.com/Homebrew/brew/issues/5513
Brew team has already released a fix for this, but it will take some time until it's officially released as a new version. Travis support is escalating this to macOS infrastructure team to see if there's a fix that they can apply manually, but in the meantime it appears that defining some brew env vars in .travis.yml configuration file will help workaround this brew issue.
> (maint) travis-ci [2762] prevent homebrew regression

- Rakefile
Previously we would sort by a string so that version 1.10.0 was "less than" 1.9.0. This commit uses the Gem::Version class to handle comparing versions.
> (maint) Handle sorting by semver

- Rakefile
Now that we are starting to ship builds for macOS mojave add 10.14 to the list of OS to check for when generating casks.
> (maint) Handle macOS 10.14 in rake task

- Casks/pdk.rb
- Casks/puppet-bolt.rb
I tried installing `pdk` and `bolt` on MacOS and got confused about where exactly the binaries were. I ended up having to use `find` which was a not-so-great user experience.
This PR fixes that gripe by instructing the user to add `/opt/puppetlabs/pdk/bin` or `/opt/puppetlabs/bolt/bin` to their `$PATH` when installing `pdk` or `bolt`.
[Relevant brew cask reference doc](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md).
> Add a caveat about the paths for pdk and bolt

- Rakefile
The 'puppet' collection is a rolling repo that tracks the latest versions of our software. This commit switches to it per a conversation with @mwaggett in Release Engineering.
I verified this would make the desired change by running the rake task locally and checking its diff to ensure that `puppet5` was replaced with `puppet`. Below is a diff of what would change if the task were run today. I am not including the run of the task as part of this PR since the versions of bolt and pdk have not yet changed.
```diff
diff --git a/Casks/pdk.rb b/Casks/pdk.rb
index c31ec45..9f84bc9 100644
--- a/Casks/pdk.rb
+++ b/Casks/pdk.rb
@@ -3,23 +3,23 @@ cask 'pdk' do
when '10.11'
os_ver = '10.11'
version '1.10.0.0'
-    sha256 '721005b6b2d367de6d7708d084db3a4dd607024fd112c33396a46c0be0f050e8'
+    sha256 …
```
> Changed collection to 'puppet' from 'puppet5'

- Formula/wash.rb
- README.md
Adds a homebrew formula for building and installing wash from scratch. This is a young project, but I don't see any obvious reason to create a new tap for it.
Supports puppetlabs/wash#241.
> Add homebrew formula for wash

- CODEOWNERS
Adds @puppetlabs/night-s-watch as codeowners for puppet-agent releases.
Signed-off-by: Michael Smith <michael.smith@puppet.com>
> Add codeowner's for the puppet-agent release

- Formula/wash.rb
This installs `realpath`, which Wash uses to provide its shell prompt.
Coreutils will be installed by default, but use `recommended` to provide
the option to install without it because `coreutils` brings in several
applications that conflict with other packages. A future version of Wash
will include a fix for https://github.com/puppetlabs/wash/issues/492
that degrades gracefully if `realpath` is not present.
Signed-off-by: Michael Smith <michael.smith@puppet.com>
> Add a recommended dependency on coreutils

- Casks/puppet-agent.rb
This commit updates Homebrew to get the latest version of puppet-agent
> (PA-2891) Update Homebrew puppet-agent to 6.9.0

- .travis.yml
- CODEOWNERS
- Casks/pe-client-tools-2018.1.rb
- Casks/pe-client-tools-2019.3.rb
- Casks/pe-client-tools.rb
- README.md
- Rakefile
- templates/pe-client-tools-2018.1.rb.erb
- templates/pe-client-tools-2019.3.rb.erb
- templates/pe-client-tools.rb.erb
This commit also includes the following related changes:
- updates the CODEOWNERS file to indicate that the Skeletor owns
pe-client-tools
- Also added cells in Travis CI for macOS 10.12, 10.13, & 10.14
- Refactors fetching url's to resolve an error discoved while trying to
download from s3
Fixes #70
> Adds a Cask for PE Client Tools

- Casks/puppet-agent-6.rb
- Casks/puppet-agent.rb
- Rakefile
Adding MacOSX 10.15 Catalina with Puppet Agent 6.13.0 release.
> (PA-3123) Update Homebrew Puppet (Puppet Agent 6.13.0)

- Formula/relay.rb
- README.md
Currently this is built as `nebula` but until that changes
over we'll just install it as `relay`.
> Add a homebrew formula for the relay.sh CLI

- Casks/pdk.rb
Also removes the post-install permissions fix for 1.16.0.1. Everyone
should be upgraded off that build by now since it was pretty
non-functional.
> (PDK-1665) Update for PDK 1.18.1.0 release

- Casks/puppet-agent-6.rb
- Casks/puppet-agent.rb
- Rakefile
Update puppet-agent versions to reflect latest status.
This changes the rolling puppet-agent cask to point to puppet7, and updates the versions on the puppet6 cask.
> (maint) Update puppet-agent versions

- Formula/wash.rb
- README.md
homebrew released version 2.7.0 on December 21st
announcement blog: https://brew.sh/2020/12/21/homebrew-2.7.0/
In the change notes under the item "Additional API deprecations,
disables and removals." this PR is linked:
https://github.com/Homebrew/brew/pull/10056
In this PR, `brew cask` was moved from deprecated to disabled. If users
try to install software this way, they get a message like this now:
```
$ brew cask install puppetlabs/puppet/pdk
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 7 formulae.
==> Updated Casks
Updated 2 casks.
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```
> (docs) Update brew install instructions

- .travis.yml
puppet-agent formula was updated to puppet 7.
Update the travis matrix to remove the checks on
OS X 10.12/10.13 for puppet-agent 7.
> (maint) remove OS X 10.12/10.13 from agent matrix

- .travis.yml
- Casks/puppet-bolt@2.rb
- README.md
We're planning to release Bolt 3.0 shortly. With most package managers
users can specify an older Bolt version if they aren't ready to upgrade,
but with homebrew we need to provide a separate puppet-bolt@2 package
for users who aren't ready to join the 3.x stream. This stream should
never be updated, it just exists so that homebrew users can easily
install Bolt 2.x.
> Add puppet-bolt@2 Cask for users who aren't ready to upgrade

- README.md
It seems like the puppet-bolt@2 package isn't available as a Cask, but
can be installed once the puppet-bolt Cask is installed. This updates
the installation instructions to install the puppet-bolt cask first,
then install the `puppet-bolt@2` formula.
> (docs) Updated README with correct installation instructions

- .travis.yml
- Casks/pe-client-tools-2018.1.rb
- Casks/pe-client-tools-2019.8.rb
- Casks/pe-client-tools.rb
- README.md
- Rakefile
- templates/pe-client-tools-2019.8.rb.erb
This incorporates the changes from #259 and #273, and removes EOL platform/project combinations from .travis.yml. The readme was also updated to reflect the current supported versions of puppet-agent and pe-client-tools.
> PE Client Tools updates and travis cleanup

- Casks/puppet-bolt.rb
- Rakefile
This updates puppet-bolt packages to 3.11.0.
This also updates the rake task to include the macOS 11 package for
puppet-bolt. Previously, the puppet-tools collection was used to
determine the OS versions to include in the puppet-bolt cask. However,
the puppet-tools collection includes pdk, which does not ship for macOS
11 currently, necessitating additional logic to not include macOS 11 in
the list of OS versions for any puppet-tools package other than
puppet-bolt.
> (maint) Update puppet-bolt to 3.11.0

- Casks/puppet-agent-5.rb
Installing puppet-agent-5 generates the following warning now:
```shellsession
$ brew install puppet-agent-5
Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.
Please report this issue to the puppetlabs/puppet tap (not Homebrew/brew or Homebrew/core):
/usr/local/Homebrew/Library/Taps/puppetlabs/homebrew-puppet/Casks/puppet-agent-5.rb:29
```
[Per the Homebrew Cask Cookbook][1], the available values for `depends_on macos` now start with `:el_capitan`, so I take it Homebrew no longer supports anything before Yosemite. So removing this line from the Cask definition should fix this warning with no ill effects.
Resolves #347.
[1]: https://docs.brew.sh/Cask-Cookbook#depends_on-macos
> (packaging) Remove deprecated Yosemite dependency

- Casks/puppet-agent-6.rb
- Casks/puppet-agent-7.rb
- Rakefile
Also removed 10.14 since it is EOL for over half a year and we aren't releasing new agents for it.
> (PA-4534) Update the shas for 6.28.0 and 7.18.0

- Casks/puppet-agent-5.rb
This produces the following:
$ brew install puppetlabs/puppet
...
==> Caveats
puppet-agent-5 has been deprecated in favor of puppet-agent-7.
brew install --cask puppet-agent-7
puppet-agent-5 has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of macOS.
> (PA-4564) Puppet 5 is EOL

- Casks/puppet-bolt.rb
- Rakefile
- templates/puppet-bolt.rb.erb
also
(maint) Guard cask:brew task arm64 lookup for non puppet-agent
b92dab4 updated the Rakefile to lookup arm64 shas for puppet-agent.
Bolt doesn't have arm64 packages (BOLT-1604 is pending). Right now only
puppet-agent has arm64 packages so added a check for pkg to skip
attempting to fetch arm64 if not puppet-agent.
> Release puppet bolt 3.26.2

- Casks/puppet-bolt.rb
- templates/puppet-bolt.rb.erb
The x86 emulator for macOS has been working for existing bolt users. This commit backs out a change from https://github.com/puppetlabs/homebrew-puppet/pull/365 while providing a path forward for when we do get to packaging for ARM.
> (maint) Continue to install x86 packages on ARM for bolt

- Casks/puppet-agent-7.rb
- Casks/puppet-agent-8.rb
- Casks/puppet-agent.rb
Also dropping support for macos 10.15.
> (PA-5603) Update for puppet-agent's 7.25.0 and 8.1.0

- .github/workflows/install.yaml
- Casks/puppet-agent-7.rb
- Casks/puppet-agent-8.rb
- Casks/puppet-agent.rb
- Rakefile
This PR:
- Adds the latest two puppet-agents to casks
- Adds support for macOS 13
- Removes support for macOS 10.15
- Updates some deprecated code and logic behaving unexpectedly
> Add puppet-agent 7.26.0 and 8.2.0

- .github/workflows/install.yaml
The Checkout GitHub Action v3 uses Node 16, which hit end-of-life on September 11, 2023.
This commit updates all instances of the Checkout Action from v3 to v4.
> (PA-5799) Update Checkout GitHub Action

- Formula/berkely-db.rb
Formula added as current homebrew version brings on openssl v3, which causes conflict errors with the PDK.
> (CAT-270) Add berkely-db formula

- .github/workflows/install.yaml
This commit adds a macOS 14 (Sonoma) GitHub Actions runner to the installation matrix used to test various Puppet projects.
> Add macOS 14 (Sonoma) to install matrix

- Casks/pdk.rb
This also adds `MacOS.version` 13, and simplifies the logic a bit: There is no reason to check `arch` in each `MacOS.version` case when `arch` is set at the top to `x86_64`. Also don't repeat the `version` call.
> pdk: update cask to PDK 3.2.0.1

- .github/workflows/install.yaml
macOS 11 (Big Sur) went end-of-life in 2023 and GitHub removed its macos-11 runners on June 28th, 2024: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
This commit removes macos-11 runners from our tests.
> Removes macOS 11 runners

- .github/workflows/install.yaml
- CODEOWNERS
- Formula/relay.rb
- Formula/wash.rb
- README.md
This PR adds deprecation warnings to projects that have been long archived.
> Formula deprecations

- .github/workflows/install.yaml
This PR removes end-of-life versions of macOS and the end-of-life PE 2019.8 client tools.
> Remove Monterey, 2019.8 client tools
